set -g mouse on

unbind C-b
set -g prefix C-a

set-option -g detach-on-destroy off

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi v send-keys -X begin-selection

bind '|' split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
bind _ split-window -v -c '#{pane_current_path}'

unbind C-s
bind s run-shell "tmux popup -E -w 80% -h 50% -T 'Select Session' 'bash ${HOME}/dotfiles/assets/scripts/tmux_fzf.sh'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "arcticicestudio/nord-tmux"

run '~/.tmux/plugins/tpm/tpm'

run-shell "${HOME}/dotfiles/assets/scripts/tmux_sessions.sh"
